/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_yongjili_ambienttemperature_MainActivity */


#define celToFar(cel) (cel * 9 / 5 + 32)
#define farToCel(far) ((far - 32) * 5 / 9)
/*
 * Class:     com_yongjili_ambienttemperature_MainActivity
 * Method:    celToFar
 * Signature: (F)F
 */

JNIEXPORT jfloat JNICALL Java_com_yongjili_ambienttemperature_MainActivity_celToFar
        (JNIEnv *env, jobject instance, jfloat cel){
        return celToFar(cel);
}

/*
 * Class:     com_yongjili_ambienttemperature_MainActivity
 * Method:    farToCel
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_yongjili_ambienttemperature_MainActivity_farToCel
        (JNIEnv *env, jobject instance, jfloat far){
        return farToCel(far);
}

/*
 * Class:     com_yongjili_ambienttemperature_MainActivity
 * Method:    dayInfoListToFar
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_yongjili_ambienttemperature_MainActivity_dayInfoListToFar
       (JNIEnv *env, jobject instance, jobject dayInfoList) {

        jclass listClass = (*env)->FindClass(env, "java/util/List");
        jmethodID listGet = (*env)->GetMethodID(env, listClass, "get", "(I)Ljava/lang/Object;");

        jmethodID listSize = (*env)->GetMethodID(env, listClass, "size", "()I");

        jclass dayInfoClass = (*env)->FindClass(env, "com/yongjili/ambienttemperature/DayHelper");
        jmethodID dayInfoGetTemperature = (*env)->GetMethodID(env, dayInfoClass, "getTemperature",
                                                              "()F");
        jmethodID dayInfoSetTemperature = (*env)->GetMethodID(env, dayInfoClass, "setTemperature",
                                                              "(F)V");

        jint len = (*env)->CallIntMethod(env, dayInfoList, listSize);
        int i;
        for (i = 0; i < len; i++) {
                jobject dayInfoObject = (*env)->CallObjectMethod(env, dayInfoList, listGet, i);
                jfloat temp = (*env)->CallFloatMethod(env, dayInfoObject, dayInfoGetTemperature);
                temp = celToFar(temp);
                (*env)->CallVoidMethod(env, dayInfoObject, dayInfoSetTemperature, temp);
        }
       return dayInfoList;
}

/*
 * Class:     com_yongjili_ambienttemperature_MainActivity
 * Method:    dayInfoListToCel
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_yongjili_ambienttemperature_MainActivity_dayInfoListToCel
        (JNIEnv *env, jobject instance, jobject dayInfoList) {
                jclass listClass = (*env)->FindClass(env, "java/util/ArrayList");
                jmethodID listGet = (*env)->GetMethodID(env, listClass, "get", "(I)Ljava/lang/Object;");
                jmethodID listSize = (*env)->GetMethodID(env, listClass, "size", "()I");

                jclass dayInfoClass = (*env)->FindClass(env, "com/yongjili/ambienttemperature/DayHelper");
                jmethodID dayInfoGetTemperature = (*env)->GetMethodID(env, dayInfoClass, "getTemperature",
                                                                      "()F");
                jmethodID dayInfoSetTemperature = (*env)->GetMethodID(env, dayInfoClass, "setTemperature",
                                                                      "(F)V");

                jint len = (*env)->CallIntMethod(env, dayInfoList, listSize);

                for (int i = 0; i < len; i++) {
                        jobject dayInfoObject = (*env)->CallObjectMethod(env, dayInfoList, listGet, i);
                        jfloat temp = (*env)->CallFloatMethod(env, dayInfoObject, dayInfoGetTemperature);
                        temp = farToCel(temp);
                        (*env)->CallVoidMethod(env, dayInfoObject, dayInfoSetTemperature, temp);
                }
                return dayInfoList;
        }





